#!/bin/sh

# 打印函数
function print(){
    echo "[CheckStyle]$*"
}

print 开始检查代码，祝你好运...

wd=`pwd`
print "当前工作目录：$wd"

check_jar_path="$wd/codestyle/checkstyle/checkstyle-8.26-all.jar"
check_xml_path="$wd/codestyle/checkstyle/checkstyle.xml"
resultParentDir="$wd/target"
result_temp_file="$resultParentDir/CheckStyleResult.log"

# print $check_jar_path $check_xml_path
# 准备结果输出文件
if [ ! -d "$resultParentDir" ];
then 
	mkdir $resultParentDir
fi

# 清空temp文件
print "清空检查结果临时文件：$result_temp_file"
rm -f $result_temp_file


is_err=0
for file in `git status --porcelain | sed s/^...// | grep '\.java$'`;do
    path="$wd/$file"
    print "Checking：$path"
    re=`java -jar $check_jar_path -c $check_xml_path $path >> $result_temp_file`
    err=`cat $result_temp_file | grep "ERROR"`
    if [[ $err = *"ERROR"* ]];then
        # print $err
        is_err=1
    fi
done

print "检查完成！"

# rm -f result_temp_file

if [ $is_err -ne 0 ]
then
	print
	print
	print "=============CodeStyle ERROR=============="
    print "你的代码不符合规范，请用IDE CheckStyle插件检查或查看log: $result_temp_file"
	print "========================================="
	print
	print
    exit 1
fi

exit 0